version: '3'
services:

  findthem-database:
    image: mysql:5.6
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: 'findthem_bd'
      MYSQL_USER: 'root'
      MYSQL_PASS: ''
      MYSQL_TCP_PORT: '3306'
    expose:
      - "3306"